### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by JF10R**
Fixed a small mistake in readme tagline noted in issue #14 .

### CODE REVIEW

**Comment by lun471k** [comment]
Just saw at least 3 other pull requests for that. closing my own.

**Comment by polianajardins** [comment]
``****``

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by polianajardins** [comment]
****

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by polianajardins** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by polianajardins** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by polianajardins** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
