### PR TITLE
Patch 2 minifycss

### PR DESCRIPTION
**Pull request by tobsn**

### CODE REVIEW

**Comment by ArtskydJ** [comment]
Why split the browserify/uglify command into 2 commands?

**Comment by polianajardins** [comment]
``

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by polianajardins** [comment]
@aweary

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by polianajardins** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tobsn** [comment]
> Why split the browserify/uglify command into 2 commands?

cleanliness? not sure

**Pull request closed without merging**
